### PR TITLE
about: Fixed broken link

### PR DESCRIPTION
**Pull request by x4m3**
donate page does not exist

### CODE REVIEW

**Comment by marcan** [comment]
Thanks! I knew I'd forgotten at least one link after renaming that page...

This is academic for the website, but can you read the DCO and add a signoff line to the commit, as mentioned in the copyright policy page? You can do sign off with `git commit -s` (or `git commit -a -s` on an existing commit).

**Comment by x4m3** [comment]
My bad, I did the edit on GitHub and forgot about the DCO (even though I read it).

Now that I think of it: I'm sure I won't be the only one forgetting to add the DCO in my commit message, maybe there could be a way with CI to check if there's a signoff in commit messages when making a pull request or something. Just a thought.

**Comment by marcan** [comment]
Thanks!

**Comment by marcan** [comment]
I just enabled a CI integration that should check for the signoffs, we'll see if it works :-)

**Pull request merged**
